### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Kens4Coding** [Kens4Coding/prework-study-guide#2]
# CSS

## User Story
I want a website showing my prework notes with **CSS** formatting to add color and shadows.

## Acceptance Criteria
When I view the Prework Study Guide website I see a dark blue header and footer and 4 boxes with a shadow.  A box each for **HTML**, **CSS**, **Git** and **Javascript**.

**Comment by abdul-rehman-dev** [comment]
Hi I m new in GitHub and open source, But have programming experience of 2 year. This is my very first comment on GitHub. 

so @Kens4Coding  you said 

> Prework Study Guide website

where is the link of this website or you are taking about index.html page of your prework-study-guide repository ? Please let me know thanks.

**Comment by Kens4Coding** [comment]
Hi there
I created this issue as part of the Denver University Coding Bootcamp pre-work exercise.  The pre-work has you build a webpage/website to enter your pre-work notes into it via a browser.  They have you use github issues to enter a TODO/requirements/acceptance criteria  list of the steps you need to take to make this webpage to hold your notes.  So this just describing the CSS for the index.hmtl page in the prework-study-guide exercise.  Are you taking this bootcamp (or already have taken it)?

**Comment by abdul-rehman-dev** [comment]
> Are you taking this bootcamp (or already have taken it)?

**NO**

Do need help in CSS to resolve your issue ??

**Comment by Kens4Coding** [comment]
Oh no, or at least not yet.
They are having me enter these issues as a todo/requirements of the "web page to hold study notes for the class".
In the pre-work I have not gotten to the CSS part yet.
But thank you for offering :)

**Comment by abdul-rehman-dev** [comment]
Okay have nice journey of development.

**Comment by Kens4Coding** [comment]
done adding CSS style sheet file
